/**
 * Reason codes dental offices see on EOBs and 835 remittances, in ClaimHive's
 * own plain-English words (not the official X12 text):
 *   - group codes (who owes the adjusted amount),
 *   - CARC: Claim Adjustment Reason Codes (why a line was adjusted or denied),
 *   - RARC: Remittance Advice Remark Codes (extra detail, often "what's missing").
 * The official lists are maintained by X12 (x12.org/codes). A code that isn't
 * here is shown as "not in ClaimHive's list" with a link to them.
 */
export type ReasonKind = "group" | "carc" | "rarc";
export type ReasonCategory =
  | "patient" | "contractual" | "missing_info" | "documentation" | "coverage" | "frequency" | "bundling" | "coding"
  | "authorization" | "timely_filing" | "duplicate" | "cob" | "necessity" | "provider" | "info";

export interface ReasonCode { kind: ReasonKind; code: string; label: string; category: ReasonCategory; action?: string }

export const CATEGORY: Record<ReasonCategory, { name: string; action: string; appealable: "yes" | "sometimes" | "no" }> = {
  patient: { name: "Patient's share", action: "This is the patient's portion under their plan (deductible, co-insurance or co-pay). Bill the patient; it isn't a denial to appeal.", appealable: "no" },
  contractual: { name: "Contract adjustment", action: "The amount above your agreed fee with this plan. Write it off; appeal only if the wrong fee schedule was applied.", appealable: "no" },
  missing_info: { name: "Missing or wrong information", action: "Fix the missing or wrong detail (tooth, surfaces, codes, IDs, dates) and send a corrected claim. Check a claim before sending catches most of these.", appealable: "sometimes" },
  documentation: { name: "Documentation needed", action: "Send what the insurer asked for (X-rays, narrative, periodontal chart, photos) with an appeal or a corrected claim. Usually winnable.", appealable: "yes" },
  coverage: { name: "Not covered / eligibility", action: "Verify the patient's eligibility and benefits. If it truly isn't covered, bill the patient (with a signed financial agreement) or another plan.", appealable: "sometimes" },
  frequency: { name: "Frequency or benefit limit", action: "Check the patient's history and the plan's limits. Appeal only with a reason the limit shouldn't apply (e.g. a documented clinical need).", appealable: "sometimes" },
  bundling: { name: "Bundled with another service", action: "If the service was separate and distinct, appeal with a narrative explaining why; otherwise it's included in the other procedure's fee.", appealable: "sometimes" },
  coding: { name: "Coding problem", action: "Check the procedure code, tooth number, surfaces and any modifiers against the chart, then send a corrected claim.", appealable: "sometimes" },
  authorization: { name: "Pre-authorization", action: "If you had a pre-authorization, appeal with its number; if not, request one and ask the plan about retro-authorization.", appealable: "sometimes" },
  timely_filing: { name: "Filed too late", action: "Appeal only with proof you filed in time (a clearinghouse acceptance report). Send claims within days of the visit.", appealable: "sometimes" },
  duplicate: { name: "Duplicate", action: "Check whether the original claim was paid. Don't resend the same claim; send a corrected claim if something changed.", appealable: "no" },
  cob: { name: "Other insurance (coordination of benefits)", action: "Bill the primary plan first, then send its EOB to this plan. Update the patient's other-insurance details.", appealable: "sometimes" },
  necessity: { name: "Medical necessity", action: "Appeal with a narrative, X-rays and chart notes showing why the treatment was needed.", appealable: "yes" },
  provider: { name: "Provider or network", action: "Check the dentist's credentialing, NPI and network status with this plan; correct the provider details and resubmit.", appealable: "sometimes" },
  info: { name: "Information", action: "Informational. Read it with the other codes on the same line; usually nothing to do.", appealable: "no" },
};

const g = (code: string, label: string, category: ReasonCategory, action?: string): ReasonCode => ({ kind: "group", code, label, category, action });
const c = (code: string, label: string, category: ReasonCategory, action?: string): ReasonCode => ({ kind: "carc", code, label, category, action });
const r = (code: string, label: string, category: ReasonCategory, action?: string): ReasonCode => ({ kind: "rarc", code, label, category, action });

export const REASON_CODES: ReasonCode[] = [
  g("CO", "Contractual obligation: the office can't bill the patient for this amount", "contractual", "The practice absorbs this amount (write-off or denial). If it's a denial rather than a fee-schedule write-off, look at the reason code to see if it can be fixed or appealed."),
  g("PR", "Patient responsibility: the patient may be billed for this amount", "patient"),
  g("OA", "Other adjustment: neither the office nor the patient is assigned this amount (often other insurance)", "info", "Often coordination of benefits or a prior payment. Read the reason code with it."),
  g("PI", "Payer-initiated reduction: the payer reduced it, and the patient can't be billed", "contractual", "Treat like CO: not billable to the patient. Appeal if the reduction is wrong."),

  c("1", "Deductible amount", "patient"),
  c("2", "Co-insurance amount", "patient"),
  c("3", "Co-payment amount", "patient"),
  c("4", "Procedure code inconsistent with modifier or missing modifier", "coding"),
  c("5", "Procedure code inconsistent with the place of service", "coding"),
  c("6", "Procedure inconsistent with the patient's age", "coding", "Check the procedure fits the patient's age (e.g. child vs adult prophylaxis, D1120 vs D1110) and the date of birth on file."),
  c("7", "Procedure inconsistent with the patient's gender", "missing_info"),
  c("8", "Procedure code inconsistent with the provider's type or specialty", "provider"),
  c("11", "Diagnosis inconsistent with the procedure", "coding"),
  c("13", "Date of death precedes the date of service", "missing_info"),
  c("14", "Date of birth follows the date of service", "missing_info"),
  c("15", "Authorization number missing, invalid, or doesn't apply to this service or provider", "authorization"),
  c("16", "Claim lacks information or has submission/billing errors", "missing_info", "Look at the remark code (e.g. N706, N37, N75) to see what's missing, add it, and send a corrected claim."),
  c("18", "Exact duplicate claim or service", "duplicate"),
  c("19", "Work-related injury: the workers' compensation carrier's responsibility", "cob"),
  c("20", "Injury covered by a liability carrier", "cob"),
  c("21", "Injury is the no-fault carrier's responsibility", "cob"),
  c("22", "May be covered by another payer (coordination of benefits)", "cob"),
  c("23", "Adjusted for what a prior payer already paid or allowed", "cob", "Informational when this plan is secondary. Check the primary EOB was sent and applied correctly."),
  c("24", "Covered under a capitation agreement or managed care plan", "contractual"),
  c("26", "Service before coverage started", "coverage"),
  c("27", "Service after coverage ended", "coverage"),
  c("29", "Filing deadline passed", "timely_filing"),
  c("31", "Patient can't be identified as the plan's member", "missing_info", "Check the member ID, name spelling and date of birth against the insurance card, then resubmit."),
  c("32", "Patient is not an eligible dependent on this plan", "coverage"),
  c("33", "Subscriber has no dependent coverage", "coverage"),
  c("35", "Lifetime benefit maximum reached", "frequency", "The plan's lifetime maximum (common for orthodontics) is used up. Bill the patient."),
  c("39", "Denied when the authorization was requested", "authorization"),
  c("45", "Charge exceeds the fee schedule or maximum allowed amount", "contractual"),
  c("49", "Routine exam or screening service not covered", "coverage"),
  c("50", "Payer does not consider it medically necessary", "necessity"),
  c("51", "Pre-existing condition not covered", "coverage", "Often a missing-tooth clause for bridges or implants. Check the plan's rules; appeal with extraction dates if the tooth was lost while covered."),
  c("54", "Assistant or multiple providers not covered", "coverage"),
  c("55", "Procedure considered experimental or investigational", "necessity"),
  c("56", "Procedure not considered proven to be effective", "necessity"),
  c("58", "Treatment in an inappropriate or invalid place of service", "coding"),
  c("59", "Processed under multiple or same-day procedure rules", "bundling"),
  c("94", "Processed in excess of charges", "info"),
  c("95", "Plan procedures not followed", "coverage"),
  c("96", "Non-covered charge", "coverage"),
  c("97", "Included in payment for another service (bundled)", "bundling"),
  c("100", "Payment made to the patient or subscriber", "info", "The insurer paid the patient directly. Collect from the patient; check the assignment of benefits on file."),
  c("101", "Predetermination: expected payment once the treatment is done", "info", "This was a pre-treatment estimate, not a payment. Send the claim after treatment."),
  c("104", "Managed care withholding", "contractual"),
  c("107", "The related or qualifying service wasn't found on this claim", "bundling", "Some procedures are only paid with a qualifying one (e.g. a build-up with a crown). Bill them together or send the related claim details."),
  c("109", "Not covered by this payer: send to the correct payer", "cob"),
  c("110", "Billing date is before the date of service", "missing_info"),
  c("112", "Service not provided directly to the patient or not documented", "documentation"),
  c("115", "Procedure postponed, cancelled or delayed", "missing_info"),
  c("119", "Benefit maximum reached", "frequency", "The annual maximum is used up. Bill the patient, or wait for the benefit year to reset for elective treatment."),
  c("125", "Submission or billing error", "missing_info"),
  c("129", "Prior processing information appears incorrect", "missing_info"),
  c("131", "Claim-specific negotiated discount", "contractual"),
  c("133", "Pending further review", "info", "Not a denial yet. Watch for the next remittance; answer any information request quickly."),
  c("136", "Prior payer's coverage rules weren't followed", "cob"),
  c("138", "Appeal procedures not followed or appeal time limit passed", "timely_filing"),
  c("140", "Patient's ID number and name don't match", "missing_info"),
  c("142", "Monthly Medicaid patient liability amount", "patient"),
  c("144", "Incentive adjustment", "info"),
  c("146", "Diagnosis invalid for the date of service", "coding"),
  c("147", "Provider's contracted rate expired or not on file", "provider"),
  c("148", "Information from another provider was missing or incomplete", "documentation"),
  c("149", "Lifetime benefit maximum reached for this service or category", "frequency"),
  c("150", "Information doesn't support this level of service", "necessity"),
  c("151", "Information does not support this many services (frequency)", "frequency"),
  c("152", "Information doesn't support this length of service", "necessity"),
  c("155", "Patient refused the service", "info"),
  c("163", "Attachment referenced on the claim was not received", "documentation", "The claim said an attachment was coming but it didn't arrive. Resend it (with the attachment ID) and ask for reprocessing."),
  c("164", "Attachment referenced on the claim wasn't received in time", "documentation"),
  c("165", "Referral missing or exceeded", "authorization"),
  c("166", "Submitted after this payer stopped handling claims for this plan", "cob"),
  c("167", "Diagnosis not covered", "coverage"),
  c("169", "Alternate benefit provided", "coverage", "The plan paid for a cheaper alternative (e.g. an amalgam rate for a posterior composite). The difference is usually the patient's to pay; appeal with a narrative if the alternative wasn't clinically appropriate."),
  c("170", "Not paid when performed or billed by this type of provider", "provider"),
  c("172", "Not paid when performed by a provider of this specialty", "provider"),
  c("177", "Patient hasn't met the eligibility requirements", "coverage"),
  c("179", "Patient hasn't met the waiting period", "coverage", "Many dental plans have waiting periods for major work. Check the plan's effective date and waiting period; bill the patient or reschedule."),
  c("181", "Procedure code invalid on the date of service", "coding", "The code wasn't valid on that date (CDT codes change every January). Use the code in effect on the date of service."),
  c("182", "Modifier invalid on the date of service", "coding"),
  c("185", "Rendering provider not eligible to perform this service", "provider"),
  c("187", "Consumer spending account payment (HSA/FSA)", "info"),
  c("189", "Unlisted procedure code billed when a specific code exists", "coding"),
  c("192", "Non-standard adjustment code from a paper remittance", "info"),
  c("193", "Original decision upheld on review", "info", "Your appeal or reconsideration was reviewed and the denial stands. Consider a second-level appeal with new evidence, or close it."),
  c("197", "Prior authorization absent", "authorization"),
  c("198", "Prior authorization exceeded", "authorization"),
  c("200", "Service during a lapse in coverage", "coverage"),
  c("202", "Personal comfort or convenience service not covered", "coverage"),
  c("203", "Discontinued or reduced service", "info"),
  c("204", "Not covered under the patient's current plan", "coverage"),
  c("206", "NPI missing", "missing_info"),
  c("207", "NPI invalid", "missing_info"),
  c("208", "NPI doesn't match the provider on file", "provider"),
  c("209", "Can't be collected from the patient, but may be billed to another payer", "cob"),
  c("210", "Pre-authorization not received in time", "authorization"),
  c("212", "Administrative surcharges not covered", "coverage"),
  c("215", "Based on a third-party settlement (subrogation)", "cob"),
  c("216", "Based on a review organization's findings", "necessity"),
  c("222", "Exceeds the contracted maximum number of units for this period", "frequency"),
  c("223", "Adjustment required by law or regulation", "info"),
  c("224", "Patient's identity compromised (identity theft)", "missing_info"),
  c("225", "Penalty or interest payment by the payer", "info"),
  c("226", "Information requested from the provider was not sent, late, or incomplete", "documentation", "The insurer asked you for something (records, X-rays, a narrative) and didn't get it. Send it now with a request to reprocess."),
  c("227", "Information requested from the patient was not sent or incomplete", "documentation", "The insurer is waiting on the patient (often a coordination-of-benefits questionnaire). Ask the patient to call the plan."),
  c("228", "Requested information wasn't given to a previous payer", "cob"),
  c("231", "Mutually exclusive procedures on the same day", "bundling"),
  c("234", "This procedure is not paid separately", "bundling"),
  c("235", "Sales tax", "info"),
  c("239", "Claim spans eligible and ineligible coverage periods: bill separately", "coverage"),
  c("242", "Services not provided by network providers", "provider"),
  c("243", "Services not authorized by network providers", "authorization"),
  c("246", "Reporting-only code: not payable", "info"),
  c("250", "Wrong attachment received", "documentation"),
  c("251", "Attachment received was incomplete or deficient", "documentation"),
  c("252", "An attachment or other documentation is required", "documentation"),
  c("253", "Sequestration: reduction in federal payment", "contractual"),
  c("254", "Dental plan: not a dental benefit; submit to the patient's medical plan", "cob", "Some oral surgery and trauma care is billed to medical insurance. Send it to the patient's medical plan."),
  c("256", "Not payable under the managed care contract", "contractual"),
  c("257", "Pending: premium payment grace period", "coverage"),
  c("261", "Procedure inconsistent with the patient's history", "frequency", "Often a procedure already done on that tooth (e.g. a second root canal or a crown within the replacement period). Check the history; appeal with a narrative if clinically needed."),
  c("269", "Anesthesia not covered for this service", "coverage"),
  c("270", "Medical plan: not a medical benefit; submit to the patient's dental plan", "cob"),
  c("272", "Coverage or program guidelines not met", "coverage"),
  c("273", "Coverage or program guidelines exceeded", "frequency"),
  c("275", "Prior payer's patient responsibility not covered", "cob"),
  c("276", "Services denied by the prior payer aren't covered by this payer", "cob"),
  c("A1", "Claim or service denied (general)", "info", "A general denial: the remark codes on the same line say why."),
  c("B1", "Non-covered visits", "coverage"),
  c("B7", "Provider not certified or eligible for this service on this date", "provider"),
  c("B11", "Transferred to the correct payer for processing", "cob"),
  c("B12", "Service not documented in the patient's record", "documentation"),
  c("B13", "Previously paid", "duplicate"),
  c("B14", "Only one visit or consultation per provider per day is covered", "frequency"),
  c("B15", "Needs a qualifying service that wasn't received or covered", "bundling"),
  c("B16", "\"New patient\" requirements not met", "coding", "Comprehensive exams (D0150) are often limited to new patients or once per provider. Check the patient's history with the practice."),
  c("B20", "Service partly or fully provided by another provider", "duplicate"),
  c("B22", "Payment adjusted based on the diagnosis", "coding"),

  r("M15", "Separately billed services bundled as parts of the same procedure", "bundling"),
  r("M51", "Missing, incomplete or invalid procedure code", "coding"),
  r("M54", "Missing, incomplete or invalid total charges", "missing_info"),
  r("M62", "Missing, incomplete or invalid authorization number", "authorization"),
  r("M67", "Missing, incomplete or invalid other procedure code", "coding"),
  r("M76", "Missing, incomplete or invalid diagnosis", "missing_info"),
  r("M77", "Missing, incomplete or invalid place of service", "missing_info"),
  r("M79", "Missing, incomplete or invalid charge", "missing_info"),
  r("M80", "Not covered on the same date as a service already processed for this patient", "bundling"),
  r("M81", "Code to the highest level of specificity", "coding"),
  r("M86", "Already paid for the same or a similar procedure within the time limit", "frequency"),
  r("M127", "Missing patient medical/dental record for this service", "documentation"),
  r("MA04", "Secondary payment needs the primary payer's details or payment", "cob"),
  r("MA27", "Missing, incomplete or invalid member name or ID", "missing_info"),
  r("MA61", "Missing, incomplete or invalid subscriber or member ID number", "missing_info"),
  r("MA130", "Claim has incomplete or invalid information", "missing_info", "The claim couldn't be processed as sent, so there's nothing to appeal. Fix it and send a new claim."),
  r("N4", "Missing, incomplete or invalid prior insurer's EOB", "cob"),
  r("N10", "Adjusted after review by a dental consultant or peer review", "necessity", "A dental consultant reviewed it. Appeal with more clinical evidence (X-rays, perio charting, narrative)."),
  r("N14", "Payment based on a contracted amount or fee schedule", "contractual"),
  r("N19", "Procedure incidental to the main procedure", "bundling"),
  r("N20", "Service not payable with other service on the same date", "bundling"),
  r("N23", "Patient's share may change due to other insurance or benefit maximums", "info"),
  r("N29", "Missing documentation, notes, report or chart", "documentation"),
  r("N30", "Patient ineligible for this service", "coverage"),
  r("N34", "Wrong claim form or format for this service", "missing_info"),
  r("N35", "Program integrity or utilization review decision", "necessity"),
  r("N37", "Missing, incomplete or invalid tooth number or letter", "missing_info", "Add the tooth number (1-32, or A-T for primary teeth) and send a corrected claim."),
  r("N39", "Procedure code doesn't fit the tooth number or letter", "coding", "Check the tooth against the procedure (e.g. an anterior root canal code on a molar) and correct one or the other."),
  r("N40", "Missing X-rays or images", "documentation", "Send the X-rays (dated, labelled with the tooth) and ask for reprocessing."),
  r("N48", "Claim doesn't match what the other insurer reported", "cob"),
  r("N52", "Patient not enrolled in your managed care plan on this date", "coverage"),
  r("N54", "Claim doesn't match the pre-authorized services", "authorization"),
  r("N56", "Procedure code not valid for the service or date", "coding"),
  r("N59", "See your provider manual for program details", "info"),
  r("N63", "Bill these services on separate claim lines", "missing_info"),
  r("N65", "Procedure rate not on file for this date or provider", "provider"),
  r("N75", "Missing, incomplete or invalid tooth surface", "missing_info", "Add the surfaces (M, O, D, B/F, L/I) that match the chart and send a corrected claim."),
  r("N95", "This provider type or specialty may not bill this service", "provider"),
  r("N102", "Denied without reviewing records because they weren't received in time", "documentation"),
  r("N130", "Check plan benefit documents for limits", "frequency"),
  r("N179", "More information requested from the member; will be reconsidered once received", "documentation"),
  r("N180", "Doesn't meet the criteria for the category it was billed under", "coding"),
  r("N182", "Must be billed according to this plan's schedule", "coding"),
  r("N202", "More information or explanation will be sent separately", "info"),
  r("N216", "Service not covered, or patient not enrolled in this part of the plan", "coverage"),
  r("N257", "Missing, incomplete or invalid billing provider identifier", "missing_info"),
  r("N258", "Missing, incomplete or invalid billing provider address", "missing_info"),
  r("N286", "Missing, incomplete or invalid referring provider identifier", "missing_info"),
  r("N290", "Missing, incomplete or invalid rendering provider identifier", "missing_info"),
  r("N329", "Missing, incomplete or invalid patient date of birth", "missing_info"),
  r("N350", "Missing description for an unlisted (\"by report\") procedure", "documentation", "Unlisted codes (e.g. D2999) need a narrative describing what was done. Resubmit with it."),
  r("N356", "Not covered with, or after, a non-covered service", "coverage"),
  r("N362", "Number of services exceeds what the plan allows", "frequency"),
  r("N379", "Claim-level details don't match the line-level details", "missing_info"),
  r("N381", "See your contract for restrictions or payment details", "contractual"),
  r("N382", "Missing, incomplete or invalid patient identifier", "missing_info"),
  r("N390", "This service can't be billed separately", "bundling"),
  r("N408", "This payer doesn't cover a previous payer's deductible", "cob"),
  r("N418", "Misrouted claim: see the payer's submission instructions", "cob"),
  r("N425", "Excluded service", "coverage"),
  r("N428", "Not covered in this place of service", "coverage"),
  r("N431", "Not covered with this procedure", "bundling"),
  r("N435", "Over the allowed frequency without supporting documentation", "frequency", "Send documentation of why more services were needed (e.g. perio charting for extra cleanings)."),
  r("N441", "Missed or cancelled appointment not covered", "coverage"),
  r("N448", "Not in the fee schedule or contracted fees", "contractual"),
  r("N479", "Missing EOB from the other insurer", "cob"),
  r("N525", "Not covered within the global period of another service", "bundling"),
  r("N587", "Policy benefits exhausted", "frequency"),
  r("N640", "Exceeds the number or frequency allowed in the time period", "frequency"),
  r("N657", "Bill with the correct code for these services", "coding"),
  r("N674", "Not covered unless a prerequisite service was provided", "bundling"),
  r("N705", "Incomplete or invalid documentation", "documentation"),
  r("N706", "Missing documentation", "documentation"),
  r("N822", "Missing procedure modifier", "coding"),
  r("N823", "Incomplete or invalid procedure modifier", "coding"),
];

const KEY = (kind: ReasonKind, code: string) => `${kind}:${code.toUpperCase()}`;
const BY_KEY = new Map(REASON_CODES.map((x) => [KEY(x.kind, x.code), x]));

export function findReason(kind: ReasonKind, code: string): ReasonCode | undefined {
  return BY_KEY.get(KEY(kind, code));
}
export const actionFor = (x: ReasonCode) => x.action ?? CATEGORY[x.category].action;
export const anchorFor = (kind: ReasonKind, code: string) => `${kind}-${code.toUpperCase()}`;
/** Where a code is explained: the lookup page, filtered to it. */
export const codeHref = (kind: ReasonKind, code: string) => `/app/codes?q=${encodeURIComponent(code)}#${anchorFor(kind, code)}`;

/** Search by code (exact or prefix, with or without group, e.g. "CO-16") or by words in the text. */
export function searchReasons(q: string): ReasonCode[] {
  const s = q.trim().toUpperCase().replace(/^(CO|PR|OA|PI)[\s-]+(?=\w)/, "");
  if (!s) return REASON_CODES;
  const exact = REASON_CODES.filter((x) => x.code.toUpperCase() === s);
  const prefix = REASON_CODES.filter((x) => x.code.toUpperCase().startsWith(s) && !exact.includes(x));
  const words = s.toLowerCase().split(/\s+/).filter(Boolean);
  const norm = (t: string) => t.toLowerCase().replace(/-/g, "");
  const has = (t: string) => words.every((w) => norm(t).includes(norm(w)));
  const rest = REASON_CODES.filter((x) => !exact.includes(x) && !prefix.includes(x));
  // Codes whose name matches come first, then ones that only match in the advice.
  const named = rest.filter((x) => has(`${x.label} ${CATEGORY[x.category].name}`));
  const mentioned = rest.filter((x) => !named.includes(x) && has(`${x.label} ${CATEGORY[x.category].name} ${actionFor(x)}`));
  return [...exact, ...prefix, ...named, ...mentioned];
}
